### PR TITLE
Ported -w wipe from ttwl-cli-saveedit

### PR DESCRIPTION
**Pull request by abramhindle**
Ported -w wipe from ttwl-cli-saveedit, it's your code :)

### CODE REVIEW

**Comment by apocalyptech** [comment]
Looks good, though would you mind pulling in the README changes as well, and maybe the Changelog entry too?  Thanks!

**Comment by abramhindle** [comment]
I'm not sure what you mean by pulling README changes?

**Comment by apocalyptech** [comment]
Oh, just the documentation stuff, eg: https://github.com/apocalyptech/ttwl-cli-saveedit/blob/master/README-saves.md#wipe-inventory

**Comment by abramhindle** [comment]
OK I added the documentation and change-log and version.

**Comment by apocalyptech** [comment]
Okay, thanks!  Merged this in w/ `--squash`, btw, 'cause I'm actually not quite ready to release a 1.16.2 yet.  I still need to test out that damned `--copy-tvhm` first.  Maybe I'll carve out some time to get that done tonight.

Anyway, the squash-merge kind of makes this PR look weird, but those changes should be in.  Thanks!

**Pull request closed without merging**
