### PR TITLE
Switch to protobuf3 which is what the files actually are

### PR DESCRIPTION
**Pull request by sandsmark**
This makes the new files written identical to the old ones, except the actual changes.

### CODE REVIEW

**Comment by sandsmark** [comment]
Fixes https://github.com/apocalyptech/bl3-cli-saveedit/issues/1

**Comment by apocalyptech** [comment]
Ah, nice catch!  I'll dig into this a bit and get it merged in a bit.  I do notice that you were probably a bit overzealous with removing the `optional` from the protobuf definitions...  For example `enable_optional_vo` inside OakProfile's `Profile`, and `optional_objective_reward_fixup_applied` inside OakSave's `Character`.  :)

**Comment by apocalyptech** [comment]
Well I probably should've just tweaked this PR to clean up those couple of `optional_` named vars, but ended up just committing those myself out on the main branch.  So I'm gonna close this PR without actually officially merging it, but all your changes (including the couple of changes which weren't specifically protobuf-related) are now in HEAD.

Thanks a bunch, appreciate it!

**Comment by sandsmark** [comment]
oh, doh, I just did a search and replace for optional, and didn't bother wrapping it with \d... sorry for that.

**Comment by apocalyptech** [comment]
No worries!  Quite happy to have PRs sent in here.  :)

**Pull request closed without merging**
